### ISSUE TITLE
Last card option doesn't work

### ISSUE THREAD

**Issue by heyrocker** [haugstrup/matchplay-issues#1]
If I create a series and choose for it to be card based, the tournament summary does not reflect the values I input. This is the same for the individual weeks as well. Additionally I chose "Keep last card entered" and it is not doing this, it is giving best game. You'll see in my December #1 test tournament that Derek Miazga has two cards, and the second one entered is lower but it didn't get kept.

(These may be two bugs and not one)

**Comment by haugstrup** [comment]
It was two bugs. The tournament creation form was borked because I refactored something right before emailing you (story of my life). That bug I fixed right away. The second bug was what you outlined in #5. That bug I have fixed, but not yet deployed
