### ISSUE TITLE
Ability to add players in the scorekeeper when creating a card

### ISSUE THREAD

**Issue by heyrocker** [haugstrup/matchplay-issues#3]
Is this possible for situations in which players don't have to do a separate registration step?

**Comment by haugstrup** [comment]
It's not, but it's something that's very important to a very small group of TDs. Basically for tournaments where a bartender/store manager is on location to enter scores and it's a bad idea for the TD to leave their MP account logged in.

The self-registration is what you can do today. I *will* make it possible for a scorekeeper to add players to the tournament (as a configuration option), but it won't be part of the card format rollout. It'll be later (likely much later) as it's own separate feature for any tournament
