### ISSUE TITLE
Card calculation isssue

### ISSUE THREAD

**Issue by heyrocker** [haugstrup/matchplay-issues#5]
In week 2 of the December Superleague Test, I entered two cards for Andy Cobb. One was erroneous and the second one was correct. This tournament is setup for "Last card counts" scoring. Here you can see Andy's two cards:

https://matchplay.events/live/8y65/players/19480

His scores for both cards are being calculated in the final standings, for instance if you look at the Arena scores for World Cup Soccer here:

https://matchplay.events/live/8y65/scores?arena_id=3792

You will see both his scores on that game are being counted and added in for totals. Additionally, even though both scores are exactly the same, they are not counting as a tie, but one is given 83 points while the other is given 82. 

If you look at the total standings at 

https://matchplay.events/live/8y65/standings

You'll see that only one of his cards is listed, although the effects of him having two scores cascades throughout everyone else's totals. You can see how this should be playing out at

https://docs.google.com/spreadsheets/d/1N7oh-yEHHL8UokU3aTeM9y_1Uo_r9jCQs9nCAWkTuWQ/edit#gid=1138100669

**Comment by haugstrup** [comment]
Well that was embarrassing. I haven't deployed this yet so hold your horses :)
