### ISSUE TITLE
Ability to void / delete cards after they have been marked as complete

### ISSUE THREAD

**Issue by heyrocker** [haugstrup/matchplay-issues#6]
There should be the ability not just to modify cards after completion, but also to void them, in case someone inadvertantly marks a card as complete instead of void.

**Comment by haugstrup** [comment]
@heyrocker In your Super League: If you void a player's current card which would you expect:

* Player's second-to-latest card becomes the "best" card again
* Player will have no "best" card

I'm guessing the first option, but wanted to check
