### ISSUE TITLE
Group Match Play Finals - groups end up picking same arenas for rounds

### ISSUE THREAD

**Issue by csstup** [haugstrup/matchplay-issues#7]
Finals, settings are:
Format Group Bracket
Seeding Manual
Bracket size 8
Scoring system IFPA
Arena draws Balanced
Matches per round 3

8 players in the finals, MP sets it up as several groups, as expected.
We have 14 arenas setup in the finals.

Group 1 (4 players) plays rounds on Machines A, C, and E.
Group 2 (4 players) plays rounds on Machines E, A, and C.

Other finals we've had, each group plays a completely different set of machines, sometimes only overlapping 1 or 2 across groups in a given bracket tier. I'm guessing its what the players played least so far. 

While each round is not on the same machine at the same time, it's still overlapping such that one group has to wait for another.

Shouldn't matchplay try and assign groups to unique games within a given bracket tier?   Such that quarterfinals Group 1 and Group 2 aren't playing the same games.   Rounds are not necessarily simultaneous.

**Comment by haugstrup** [comment]
@csstup The machine assignment is such that there will be no overlapping games for game 1, or game 2 or game 3. But overall there might be overlapping games.

If you want to avoid overlapping games completely use the "machine banks" feature so each group is assigned a separate machine bank.

**Comment by csstup** [comment]
I don't think we'd want to use banks.  We want all games to be available to all players, but not assigned overlapping within a finals round.   Matchplay tries to not assign overlapping games during regular (non finals) rounds, why couldn't consider all groups as one "large group" and try not to put people on the same games?

Thanks!

**Comment by csstup** [comment]
Also - 
Not overlapping for all groups' "Game 1" doesn't really help much.

- We let players pick which game they want to start on from the multiple games in their group (in our case, 3.  the top seed gets to pick which game they want to start out on)
- Even if we played games in order (game 1, then game 2, etc), faster games will end up waiting on slower games.

Our players just don't understand why in a Arena pool of 15-20 games, MP is choosing the same 3 overlapping games for groups to play in finals rounds.

Thanks for listening!
